### ISSUE TITLE
깃허브 랭킹 허수 기능에 대해서

### ISSUE THREAD

**Issue by leehj050211** [BSSM-BGIT/BGIT-Backend#24]
현재 깃허브 허수 투표 기능이 수요일에만 투표가 가능하고 목요일에 랭킹을 처리하는 것으로 되어있는데
수요일에만 투표를 하는 것보단 커밋기록 조작이 의심된다면 신고를 해서 일정 수 이상 신고기록이 들어오면 허수 표시를 하는 것으로 하는 것이 좋을 것 같습니다.
또한 허수 투표 API에 유저 id가 필요한 것으로 보이는데 깃허브 랭킹 API에 유저 id 정보가 없어서 해당 기능을 만들 수 없으니 업데이트 해주시기 바랍니다.

**Comment by wonyongChoi05** [comment]
만약 커밋 조작이 의심되어서 신고누적이 되면 영구적으로 허수 표시하나요?
+ `또한 허수 투표 API에 유저 id가 필요한 것으로 보이는데 깃허브 랭킹 API에 유저 id 정보가 없어서 해당 기능을 만들 수 없으니 업데이트 해주시기 바랍니다.` -> 이 문제는 UserResponseDto에 같이 반환하도록 하겠습니다. @leehj050211

**Comment by leehj050211** [comment]
최근 신고기록이 없으면 풀려나는 방식이 좋을 것 같습니다. @wonyongChoi05

**Comment by wonyongChoi05** [comment]
최근 신고기록이 없다는것은 어떤기준으로 판단하나요?

**Comment by leehj050211** [comment]
말 그대로 몇 주 동안 신고가 들어왔는지 체크하면 되지 않을까요?

**Comment by wonyongChoi05** [comment]
그럼 몇 주 동안 신고가 0개이면 사라지는 방식으로 하겠습니다.

**Comment by wonyongChoi05** [comment]
1. 한 사람당 한번씩 신고할 수 있음(신고 횟수는 무제한)
2. 2주 이내에 받은 신고가 3개 이상이면 허수 등록
3. 등록된 신고는 2주마다 사라짐
4. 2주가 지나면 다시 같은사람 신고 가능
