### ISSUE TITLE
커밋 파싱 실패

### ISSUE THREAD

**Issue by wonyongChoi05** [BSSM-BGIT/BGIT-Backend#25]
🐞  Describe
커밋 파싱에 실패하는 문제

✅ Tasks
- [x] Iterator Atomic 문제
- [x] Commit REGEX는 관계 없음
- [x] 코드 간단하게 리팩터링

🙋🏻 할 말
바로 재배포 부탁드립니다. 커밋 파싱 문제 없는거 확인되면 이슈 닫아주시고, 트러블 슈팅은 이슈 또는 커맨트 달아주세요.

**Comment by leehj050211** [comment]
파싱은 되는 거 같은데 업데이트가 안됩니다!

**Comment by wonyongChoi05** [comment]
로그 보여주실 수 있나요??

**Comment by leehj050211** [comment]
보내드렸습니다!
